Update README.md
On my computer it says:

```
C:\Users\shwang>conda install -c conda-forge pyembree
Fetching package metadata .............


PackageNotFoundError: Package missing in current win-64 channels:
  - pyembree

Close matches found; did you mean one of these?

    pyembree: embree



C:\Users\shwang>conda install -c conda-forge embree
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\shwang\AppData\Local\Continuum\Anaconda3:

The following NEW packages will be INSTALLED:

    embree:    2.14.0-0      conda-forge

The following packages will be SUPERSEDED by a higher-priority channel:

    conda:     4.3.16-py36_0             --> 4.2.13-py36_0 conda-forge
    conda-env: 2.6.0-0                   --> 2.6.0-0       conda-forge

Proceed ([y]/n)? y

conda-env-2.6. 100% |###############################| Time: 0:00:00  40.52 kB/s
```